<a href="https://colab.research.google.com/github/igor2510/ocean-backend-bancodados-18-11-2021/blob/main/Untitled6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import pandas as pd
import matplotlib.pyplot as plt
import sklearn.linear_model as lm
import numpy as np
# Úteis 
import datetime as dt
from datetime import timedelta

abast = pd.read_excel('abastpend.xlsx')

abast.rename(columns={'Combustível': 'Combus','Data(Mês)':'Data','Valor Total':'Valor' },inplace= True)

abast['Data'] = pd.to_datetime(abast['Data'])
abast

                 Combus       Data       Valor     Volume
0           DIESEL S-10 2021-09-01  3391391.23  676872.05
1           DIESEL S-10 2021-10-01  3833060.45  721848.17
2           DIESEL S-10 2021-11-01  3681240.07  664723.84
3           DIESEL S-10 2021-12-01  4015300.60  725045.34
4           DIESEL S-10 2022-01-01  2524723.67  436976.75
5           DIESEL S-10 2022-02-01  2201461.95  372778.34
6          DIESEL S-500 2021-09-01   370564.20   74407.52
7          DIESEL S-500 2021-10-01   382958.65   72431.95
8          DIESEL S-500 2021-11-01   402029.14   72990.07
9          DIESEL S-500 2021-12-01   406093.93   73728.04
10         DIESEL S-500 2022-01-01   414571.74   71806.17
11         DIESEL S-500 2022-02-01   363821.25   61920.20
12   GASOLINA ADITIVADA 2021-09-01   276229.81   39685.42
13   GASOLINA ADITIVADA 2021-10-01   308603.27   43171.83
14   GASOLINA ADITIVADA 2021-11-01   266452.28   34802.96
15   GASOLINA ADITIVADA 2021-12-01   433564.99   56542.29
16   GASOLINA ADITIVADA 2022-01-01   412462.51   53297.47
17   GASOLINA ADITIVADA 2022-02-01   252862.64   32426.81
18  GASOLINA C ORIGINAL 2021-09-01   228139.03   32774.68
19  GASOLINA C ORIGINAL 2021-10-01   315927.28   44138.99
20  GASOLINA C ORIGINAL 2021-11-01   273613.93   35732.67
21  GASOLINA C ORIGINAL 2021-12-01   381269.08   49722.28
22  GASOLINA C ORIGINAL 2022-01-01   308056.88   39764.29
23  GASOLINA C ORIGINAL 2022-02-01   229218.10   29394.69
24         ETANOL COMUM 2021-09-01   109753.39   17726.91
25         ETANOL COMUM 2021-10-01   112576.12   17540.15
26         ETANOL COMUM 2021-11-01    96112.88   14168.39
27         ETANOL COMUM 2021-12-01   118129.85   17048.61
28         ETANOL COMUM 2022-01-01   130953.81   18802.43
29         ETANOL COMUM 2022-02-01    96016.14   14123.86

In [43]:
####################################
# SEPARANDO OS COMBUSTIVEIS
#####################################
DS10 = abast.loc[abast.Combus == "DIESEL S-10"]
DS500 = abast.loc[abast.Combus == "DIESEL S-500"]
ET  = abast.loc[abast.Combus == "ETANOL COMUM"]
GAS = abast.loc[abast.Combus == "GASOLINA C ORIGINAL"]
GASADIT = abast.loc[abast.Combus == "GASOLINA ADITIVADA"]
#Converter DATE para datetime e associar ao index do dateframe

DS10.index = pd.to_datetime(DS10.Data, format="%m-%d-%Y")
DS500.index = pd.to_datetime(DS500.Data, format="%m-%d-%Y")
ET.index = pd.to_datetime(ET.Data, format="%m-%d-%Y")
GAS.index = pd.to_datetime(GAS.Data, format="%m-%d-%Y")
GASADIT.index = pd.to_datetime(GASADIT.Data, format="%m-%d-%Y")
#eliminar a coluna DATE, pois ela já seria o indice
DS10.drop("Data", inplace=True, axis=1)
DS500.drop("Data", inplace=True, axis=1)
ET.drop("Data", inplace=True, axis=1)
GAS.drop("Data", inplace=True, axis=1)
GASADIT.drop("Data", inplace=True, axis=1)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4913: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [44]:
####Pegando Volume#####
XDS10 = DS10.index
YDS10VOL =DS10.Volume
YDS10VAL = DS10.Valor
XDS500 = DS500.index
YDS500VOL =DS500.Volume
YDS500VAL = DS500.Valor
XGAS = GAS.index
YGASVOL =GAS.Volume
YGASVAL = GAS.Valor
XGASADIT = GASADIT.index
YGASADITVOL =GASADIT.Volume
YGASADITVAL = GASADIT.Valor
XET = ET.index
YETVOL =ET.Volume
YETVAL = ET.Valor

DatetimeIndex(['2021-09-01', '2021-10-01', '2021-11-01', '2021-12-01',
               '2022-01-01', '2022-02-01'],
              dtype='datetime64[ns]', name='Data', freq=None)